project:
  type: website

website:
  title: "test.quarto.web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - new-page.qmd
      - about.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



